[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# async code check
[[plugins]]
repo = 'w0rp/ale'
on_source = ['lightline.vim']
book_add = '''
  let g:ale_linters = {
  \   'python': ['flake8'],
  \   'go': ['goimports', 'go vet', 'golint'],
  \ }
  let g:ale_fix_on_save = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_open_list = 1
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
  let g:indentLine_color_term = 236
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse --delimiter : --nth 3..'}, 'right:40%:wrap'))
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
