[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update ='''
  let g:dein#plugin.build = './install.sh'
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
on_i = 1

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'javascript.jsx', 'coffee']
on_i = 1

[[plugins]]
repo = 'Galooshi/vim-import-js'
build = 'npm install -g import-js'
on_ft = ['javascript', 'javascript.jsx', 'coffee']
on_i = 1

[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']
on_i = 1

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
on_ft = ['ruby']
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

[[plugins]]
repo = 'ponko2/deoplete-fish'
on_ft = ['fish']
on_i = 1

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

# syntax highlighting for pug formaly jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade']

